
#                         88                               
#                         88                               
#                         88                               
#     888888888 ,adPPYba, 88,dPPYba,  8b,dPPYba,  ,adPPYba,
#          a8P" I8[    "" 88P'    "8a 88P'   "Y8 a8"     ""
#       ,d8P'    `"Y8ba,  88       88 88         8b        
#     ,d8"      aa    ]8I 88       88 88         "8a,   ,aa
#     888888888 `"YbbdP"' 88       88 88          `"Ybbd8"'

#   =========================================================

# UNCOMMENT TO BENCHMARK
# BENCHMARK=1 && zmodload zsh/zprof

append_to_path() {
    if [[ -d $1 ]]; then
        export PATH="$PATH:$1"
    fi
}

# Path stuff

export GOPATH=$HOME/.go
append_to_path $GOROOT/bin
append_to_path $GOPATH/bin
append_to_path /opt/android-sdk/platform-tools
append_to_path /opt/ghidra
append_to_path ~/.local/bin

# ZGenom - plugin manager 
#=======================================================

if [[ ! -f "${HOME}/.zgenom/zgenom.zsh" ]]; then
  git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"
fi
source "${HOME}/.zgenom/zgenom.zsh"

# check for updates ever 7 days
zgenom autoupdate
	  		  
# only runs when .zgenom/sources/init.zsh doesn't exist
# zgenom reset - delete init.zsh

if ! zgenom saved; then  
    # Async for zsh, used by pure
    zgenom load mafredri/zsh-async
    # Load completion library for those sweet [tab] squares
    zgenom ohmyzsh lib/completion.zsh
    # Syntax highlighting for commands, load last
    zgenom load zdharma/fast-syntax-highlighting
    # substring history search
    zgenom load zsh-users/zsh-history-substring-search
    # colorful manual pages
    zgenom load ael-code/zsh-colored-man-pages
    # command not found - suggest how to install
    zgenom ohmyzsh plugins/command-not-found
    # Theme!
    zgenom load sindresorhus/pure

    # save all to init script
    zgenom save
fi

# Settings
#=======================================================

setopt rm_star_silent

# Pure prompt settings
zstyle :prompt:pure:path color '#FFBE63'
zstyle :prompt:pure:prompt:success color '#964879' 

# use terminal color on completion
eval "$(dircolors)"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# vi mode
bindkey -v
export KEYTIMEOUT=1
# fix backspace in vi mode
bindkey "^?" backward-delete-char

# Preferred editor for local and remote sessions
export EDITOR='nvim'
export VISUAL='nvim'

# custom vars
export GPG_TTY=$(tty)

# taskwarrior completion
zstyle ':completion:*:*:task:*' verbose yes
compdef _task t=task

# allow reverse completion with s-tab
bindkey -M menuselect '^[[Z' reverse-menu-complete

# history settings
HISTFILE=~/.zsh_history
HISTSIZE=20000
SAVEHIST=20000
setopt append_history
setopt inc_append_history
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_expire_dups_first
setopt hist_beep

# bind substring search keys
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# make reverse history search use what I already typed
_history-incremental-search-backward () {
    zle .history-incremental-search-backward $BUFFER
}
zle -N history-incremental-search-backward _history-incremental-search-backward

# bash shortcut for reverse history search
bindkey "^R" history-incremental-search-backward

# make thefuck work
eval $(thefuck --alias)

# Aliases
#=======================================================

alias ls="ls --color=auto"
alias la="ls -lAh"
alias ll="ls -lh"
# prompt before override
alias mv=mv -i
alias t=task
alias quotes="$EDITOR $QUOTES_PATH"
alias dot="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias wiki="pushd >/dev/null && cd ~/Documents/notes && nvim -c WikiIndex && popd >/dev/null"
alias nb=newsboat
alias open=xdg-open
alias smallpdf="ps2pdf -dPDFSETTINGS=/ebook"
alias vit="vit ready"
# use kitty wrapper shen connecting to ssh. 
# more here https://sw.kovidgoyal.net/kitty/kittens/ssh/
alias nmrestart="sudo systemctl restart NetworkManager"

# At startup
#=======================================================

# random quote print
# *spawn only on the first instance (no tmux,
# and no secondary kitty windows)

if [ -z $TMUX ]; then
    randomquote -f "/home/zenbassi/Documents-stef/notes/quotes.txt" | cowsay -f tux | lolcat -F 0.2 -t 
fi

if [[ -n "$BENCHMARK" ]]; then
    zprof > "$HOME/.zsh_benchmark"
fi
