swipe:
  3:
    left:
      sendkey: 'LEFTMETA+Y' # Switch to next workspace
      threshold: 0.7
    right:
      sendkey: 'LEFTMETA+T' # Switch to previous workspace
      threshold: 0.7
    up:
      sendkey: 'LEFTCTRL+F10' # Workspace overview
      threshold: 0.7
    down:
      sendkey: 'LEFTCTRL+F10' # Workspace overview
      threshold: 0.7
